[package]
name = "ai-risajuu-rs"
version = "0.3.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
serenity = "0.12"
gemini-rs = "2.0.0"
